// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeiculosProjetoTeste.Dados;

namespace VeiculosProjetoTeste.Migrations
{
    [DbContext(typeof(DadosContext))]
    [Migration("20180624225142_Inicial01")]
    partial class Inicial01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VeiculosProjetoTeste.Dados.CarroAcessorio", b =>
                {
                    b.Property<int>("CarroId");

                    b.Property<int>("AcessorioId");

                    b.HasKey("CarroId", "AcessorioId");

                    b.HasIndex("AcessorioId");

                    b.ToTable("CarroAcessorios");
                });

            modelBuilder.Entity("VeiculosProjetoTeste.Models.Acessorio", b =>
                {
                    b.Property<int>("AcessorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AcessorioId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(50)");

                    b.HasKey("AcessorioId");

                    b.ToTable("Acessorio");
                });

            modelBuilder.Entity("VeiculosProjetoTeste.Models.Carro", b =>
                {
                    b.Property<int>("CarroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CarroId");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnName("Cor");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnName("DataCompra");

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnName("Marca")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CarroId");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("VeiculosProjetoTeste.Dados.CarroAcessorio", b =>
                {
                    b.HasOne("VeiculosProjetoTeste.Models.Acessorio", "Acessorio")
                        .WithMany("CarroAcessorios")
                        .HasForeignKey("AcessorioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VeiculosProjetoTeste.Models.Carro", "Carro")
                        .WithMany("CarrosAcessorios")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
